name: CI/CD Pipeline
on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main", "master" ]

jobs:
  testing:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Unit Tests (заглушка)
        run: |
          echo "Running unit tests..."
          echo "Unit tests passed!" > test-results.txt

      - name: Run Integration Tests (заглушка)
        run: |
          echo "Running integration tests..."
          echo "Integration tests passed!" >> test-results.txt

      - name: Label PR if tests pass
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['test-passed']
            })

      - name: Upload test results
        uses: actions/upload-artifact@v4  # ВОТ ТУТ ИСПРАВЛЕНИЕ
        with:
          name: test-results
          path: test-results.txt
