
name: "2. Test Checks"

permissions:
  pull-requests: write
  contents: read

on: 
  workflow_run:
    workflows: ["1. Security Checks"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          ls -l
          sleep 1
          echo "All tests passed!"

      - name: Find and label PR
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            try {
              const runResponse = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id
              });
              
              const prsResponse = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: runResponse.data.head_sha
              });
              
              if (prsResponse.data.length > 0) {
                const prNumber = prsResponse.data[0].number;
                
                try {
                  await github.rest.issues.getLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: 'test-passed'
                  });
                } catch {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: 'test-passed',
                    color: '00FF00'
                  });
                }
                
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo
