name: "2. Test Checks"

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read  # для доступа к информации о workflow_run
  
on: 
  workflow_run:
    workflows: ["1. Security Checks"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "тест"
          ls -l
          echo "тест пройден"
          sleep 1

      - name: Add label to PR
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            try {
              // Получаем информацию о workflow_run
              const workflowRunId = context.payload.workflow_run.id;
              const runResponse = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: workflowRunId
              });
              
              // Получаем номер PR из head_sha
              const headSha = runResponse.data.head_sha;
              const prsResponse = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: headSha
              });
              
              if (prsResponse.data.length > 0) {
                const prNumber = prsResponse.data[0].number;
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  labels: ['test-passed']
                });
                console.log(`Added label to PR #${prNumber}`);
              } else {
                console.log('No PRs associated with this workflow run');
              }
            } catch (error) {
              console.error('Error:', error);
              core.setFailed(error.message);
            }
