name: "2. Test Checks"

permissions:
  pull-requests: write
  issues: write
  contents: read

on: 
  workflow_run:
    workflows: ["1. Security Checks"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          ls -l
          sleep 1
          echo "All tests passed!"

      - name: Get PR number
        id: get-pr
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const runResponse = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            
            const prsResponse = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: runResponse.data.head_sha
            });
            
            if (prsResponse.data.length > 0) {
              return prsResponse.data[0].number;
            }
            return -1;

      - name: Add label
        if: steps.get-pr.outputs.result != -1
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.get-pr.outputs.result }}
          labels: 'test-passed'
